image: maven:3.6.3-jdk-11

before_script:
- apt-get update && apt-get install -y openjfx

compile:
  stage: build
  script:
    - mvn compile --batch-mode

verify:
  stage: deploy
  script:
    - mvn verify --batch-mode
  artifacts:
    paths:
      - target/*.jar
    reports:
      junit: target/surefire-reports/TEST-*.xml
    expire_in: 6 weeks

