/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.omg.space.xtce.ui;

import java.awt.event.WindowEvent;
import java.math.BigInteger;
import java.util.BitSet;
import org.omg.space.xtce.toolkit.XTCEItemValue;
import org.omg.space.xtce.toolkit.XTCETypedObject;

/**
 *
 * @author David Overeem
 *
 */

public class XTCEViewerEncodeDecodeItemDialog extends javax.swing.JDialog {

    /** Constructor
     *
     * @param parent Frame object that owns this dialog box.
     *
     * @param modal Modality of the dialog box, which can be true if it blocks
     * all other window operations or false if this dialog can stand alone.
     *
     * @param item XTCETypedObject item to evaluate.
     *
     */

    public XTCEViewerEncodeDecodeItemDialog( java.awt.Frame   parent,
                                             boolean          modal,
                                             XTCETypedObject  item ) {
        super( parent, modal );
        initComponents();
        itemValueObj_ = new XTCEItemValue( item );
        setTitle( item.getName() );
        if ( item.isValid() == false ) {
            warningsText.setText( "ERROR: Invalid Type For This Item" );
            makeCalibratedButton.setEnabled( false );
            makeRawButton.setEnabled( false );
        }
        setVisible( true );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        calibratedFieldLabel = new javax.swing.JLabel();
        orLabel = new javax.swing.JLabel();
        uncalibratedFieldLabel = new javax.swing.JLabel();
        rawFieldLabel = new javax.swing.JLabel();
        binaryFieldLabel = new javax.swing.JLabel();
        warningsLabel = new javax.swing.JLabel();
        calibratedValueField = new javax.swing.JTextField();
        uncalibratedValueField = new javax.swing.JTextField();
        rawValueField = new javax.swing.JTextField();
        binaryValueField = new javax.swing.JTextField();
        makeRawButton = new javax.swing.JButton();
        makeCalibratedButton = new javax.swing.JButton();
        warningsScrollPane = new javax.swing.JScrollPane();
        warningsText = new javax.swing.JTextArea();
        dismissPanel = new javax.swing.JPanel();
        dismissButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(515, 360));

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 332));

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Generate Sample Values");

        calibratedFieldLabel.setText("Enter EU/Calibrated Value");

        orLabel.setText("OR");

        uncalibratedFieldLabel.setText("(Uncalibrated Value)");

        rawFieldLabel.setText("Enter Raw Value");

        binaryFieldLabel.setText("Raw Binary Bit Set");

        warningsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningsLabel.setText("Warnings");

        uncalibratedValueField.setEditable(false);

        binaryValueField.setEditable(false);

        makeRawButton.setText("Generate Raw");
        makeRawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeRawButtonActionPerformed(evt);
            }
        });

        makeCalibratedButton.setText("Generate EU/Calibrated");
        makeCalibratedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeCalibratedButtonActionPerformed(evt);
            }
        });

        warningsText.setColumns(20);
        warningsText.setRows(5);
        warningsScrollPane.setViewportView(warningsText);

        dismissButton.setText("Dismiss");
        dismissButton.setMaximumSize(new java.awt.Dimension(80, 25));
        dismissButton.setMinimumSize(new java.awt.Dimension(80, 25));
        dismissButton.setPreferredSize(new java.awt.Dimension(80, 25));
        dismissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismissButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dismissPanelLayout = new javax.swing.GroupLayout(dismissPanel);
        dismissPanel.setLayout(dismissPanelLayout);
        dismissPanelLayout.setHorizontalGroup(
            dismissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dismissPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dismissButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dismissPanelLayout.setVerticalGroup(
            dismissPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dismissPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(dismissButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orLabel)
                    .addComponent(rawFieldLabel)
                    .addComponent(binaryFieldLabel)
                    .addComponent(calibratedFieldLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calibratedValueField)
                    .addComponent(rawValueField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(binaryValueField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(uncalibratedValueField, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(makeCalibratedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(makeRawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(uncalibratedFieldLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(warningsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(warningsScrollPane)
            .addComponent(dismissPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calibratedFieldLabel)
                    .addComponent(calibratedValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeRawButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orLabel)
                    .addComponent(uncalibratedValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uncalibratedFieldLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rawFieldLabel)
                    .addComponent(rawValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(makeCalibratedButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(binaryFieldLabel)
                    .addComponent(binaryValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dismissPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed

        this.dispatchEvent( new WindowEvent(this, WindowEvent.WINDOW_CLOSING) );

    }//GEN-LAST:event_dismissButtonActionPerformed

    private void makeRawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeRawButtonActionPerformed

        itemValueObj_.clearWarnings();
        String calValue = (String)calibratedValueField.getText();
        BitSet bits     = itemValueObj_.encode( calValue );
        String rawValue = itemValueObj_.bitSetToHex( bits );
        String binValue = itemValueObj_.bitSetToBinary( bits );
        warningsText.setText( "" );
        for ( String warning : itemValueObj_.getWarnings() ) {
            warningsText.append( warning );
        }
        rawValueField.setText( rawValue );
        uncalibratedValueField.setText( "" );
        binaryValueField.setText( binValue );

    }//GEN-LAST:event_makeRawButtonActionPerformed

    private void makeCalibratedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeCalibratedButtonActionPerformed

        itemValueObj_.clearWarnings();
        BigInteger uncalValue = BigInteger.ZERO;
        String     rawValue   = (String)rawValueField.getText();
        rawValue = rawValue.toLowerCase();
        if ( rawValue.startsWith( "0x" ) == true ) {
            uncalValue = new BigInteger( rawValue.replaceFirst( "0x", "" ), 16 );
        } else {
            uncalValue = new BigInteger( rawValue );
        }
        BitSet bits     = itemValueObj_.encodeRawBits( uncalValue );
        String calValue = itemValueObj_.decode( bits );
        String binValue = itemValueObj_.bitSetToBinary( bits );
        warningsText.setText( "" );
        for ( String warning : itemValueObj_.getWarnings() ) {
            warningsText.append( warning );
        }
        calibratedValueField.setText( calValue );
        uncalibratedValueField.setText( uncalValue.toString() );
        binaryValueField.setText( binValue );

    }//GEN-LAST:event_makeCalibratedButtonActionPerformed


    // Private Data Members

    XTCEItemValue itemValueObj_ = null;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel binaryFieldLabel;
    private javax.swing.JTextField binaryValueField;
    private javax.swing.JLabel calibratedFieldLabel;
    private javax.swing.JTextField calibratedValueField;
    private javax.swing.JButton dismissButton;
    private javax.swing.JPanel dismissPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton makeCalibratedButton;
    private javax.swing.JButton makeRawButton;
    private javax.swing.JLabel orLabel;
    private javax.swing.JLabel rawFieldLabel;
    private javax.swing.JTextField rawValueField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel uncalibratedFieldLabel;
    private javax.swing.JTextField uncalibratedValueField;
    private javax.swing.JLabel warningsLabel;
    private javax.swing.JScrollPane warningsScrollPane;
    private javax.swing.JTextArea warningsText;
    // End of variables declaration//GEN-END:variables
}
